<?php

 /**
 * Le Raclet theme : callbacks for hooked filters and actions
 *
 * Opabinia75, opabinia@opabinia.de
 * v1 07/14
 */

/*------------------------------------------------------------------
 * EXCLUDE the individual posts from all queries.
 *-----------------------------------------------------------------*/
function lr_exclude_default_post($query) {

  if ($query->is_main_query()) {
    set_query_var('post__not_in', array(306,312));
  }
}

/*------------------------------------------------------------------
 * USE a single template for the WORKSHOP categories, regarless of
 * language.
 *-----------------------------------------------------------------*/
function lr_redirect_template($template) {

	if (function_exists('pll_is_translated_taxonomy')) {
		if (is_category('veranstaltungen')) {
			$new_template = locate_template(array( 'category-events.php'));
			if ( $new_template != NOTHING) {
				return $new_template ;
			}
		}
	}
	return $template;
}

/*------------------------------------------------------------------
 * HIDE attachment caption, alternative text and description boxes.
 * Captions and descriptions are not used at all. Instead, alt-text
 * is generated by combining parent post + attachment titles.
 *-----------------------------------------------------------------*/
function lr_hide_attachment_details() { ?>

	<script type="text/javascript">
		var $ = jQuery.noConflict();
		$(document).ready(function($){
			//$(".wp_attachment_details").hide();
			$("#wp-content-media-buttons").remove();
		});
	</script>
<?php }

/*------------------------------------------------------------------
 * PASS variables to the client-side JS when the category page is
 * loaded. These variables are used by JS to display additionnal
 * thumbails through Ajax.
 *-----------------------------------------------------------------*/
function lr_ajax_init() {

 	global $wp_query;

	if(is_category()) {

		wp_enqueue_script('lr-ajax');

		$max = $wp_query->max_num_pages;
		$paged = get_query_var('paged');

		$paged = (	get_query_var('paged') > 1) ? get_query_var('paged') : 1;

		$data = array(
			'startPage' => $paged,
			'maxPages' => $max,
			'nextLink' => next_posts($max, false)
		);
		wp_localize_script('lr-load-posts','lr_ajax',$data);
	}
}

/*------------------------------------------------------------------
 * MODIFY the the main loop query when the Polylang plugin is
 * active.
 *-----------------------------------------------------------------*/
function lr_modify_query($query) {

	if ($query->is_main_query()) {

		if ($query->is_home() && function_exists('pll_the_languages')) {

			$number_of_posts = get_option('posts_per_page');
			$number_of_languages = count(pll_the_languages(array('raw' => YES)));
			$query->set('posts_per_page', $number_of_posts * $number_of_languages);
			$query->set('lang', NOTHING);

		} elseif (is_category() && function_exists('pll_get_term')) {

			$category = get_category_by_slug($query->get('category_name'));
			$categories = lr_get_category_translations($category->term_id);
			$query->set('cat', implode(',', $categories));
			$query->set('category_name', NOTHING);
		}
	}
	return $query;
}

/*------------------------------------------------------------------
 * REMOVE metaboxes to spare the headache.
 *-----------------------------------------------------------------*/
function lr_remove_metaboxes() {

		remove_meta_box('postimagediv', 'post', 'side');
		remove_meta_box('postexcerpt', 'post', 'normal');
		remove_meta_box('revisionsdiv', 'post', 'normal');
		remove_meta_box('postcustom', 'post', 'normal');
		remove_meta_box('authordiv', 'post', 'normal');
		remove_meta_box('tagsdiv-post_tag', 'post', 'normal');
		remove_meta_box('pll-tagsdiv-post_tag', 'post', 'normal'); // When Polylang plugin is active
		remove_meta_box('postimagediv', 'page', 'side');
		remove_meta_box('pageparentdiv', 'page', 'side');
		remove_meta_box('postcustom', 'page', 'normal');
		remove_meta_box('authordiv', 'page', 'normal');
		remove_meta_box('revisionsdiv', 'page', 'normal');
}

/*------------------------------------------------------------------
 * REMOVE the clutter on the dashboard.
 *-----------------------------------------------------------------*/
function lr_clean_dashboard() {

    remove_meta_box('dashboard_right_now', 'dashboard', 'normal');   // Right Now
    remove_meta_box('dashboard_recent_comments', 'dashboard', 'normal'); // Recent Comments
    remove_meta_box('dashboard_incoming_links', 'dashboard', 'normal');  // Incoming Links
    remove_meta_box('dashboard_plugins', 'dashboard', 'normal');   // Plugins
    remove_meta_box('dashboard_quick_press', 'dashboard', 'side');  // Quick Press
    remove_meta_box('dashboard_recent_drafts', 'dashboard', 'side');  // Recent Drafts
    remove_meta_box('dashboard_primary', 'dashboard', 'side');   // WordPress blog
    remove_meta_box('dashboard_secondary', 'dashboard', 'side');   // Other WordPress News
}

/*------------------------------------------------------------------
 * REMOVE medium and large image. This theme uses only full sized
 * images and thumbnails.
 *-----------------------------------------------------------------*/
function lr_remove_image_sizes ($sizes) {

	unset($sizes['medium']);
	unset($sizes['large']);
	return $sizes;
}

function lr_enqueue_scripts() {

	wp_register_script('lr-script', get_template_directory_uri() . '/js/leraclet.js');
	wp_register_script('bootstrap-script', get_template_directory_uri() . '/bootstrap/js/bootstrap.min.js');

	wp_enqueue_script('jquery');
	wp_enqueue_script('lr-script');
	wp_enqueue_script('bootstrap-script');
}

?>